Resources:
  dynamoUsersTable:
    Type: AWS::DynamoDB::Table

    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"

      KeySchema:
        - AttributeName: "username" #Partition key
          KeyType: "HASH"

      TableName: "Users"

      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
